#!/usr/bin/env node

import { readFile, writeFile, mkdir, copyFile, readdir, stat } from "fs/promises";
import { join, dirname, relative } from "path";
import { Command } from "commander";
import packageJson from "../package.json";

async function fetchItemIdsJson(): Promise<string> {
    const response = await fetch('https://raw.githubusercontent.com/JohnScience/mcbe-item-ids/refs/heads/main/mcbe-item-ids-scraper/output/latest.json');
    if (!response.ok) {
        throw new Error(`Failed to fetch item IDs JSON: ${response.statusText}`);
    }
    return await response.text();
}

async function loadItemIdsJson(inputPath?: string): Promise<string> {
    if (inputPath) {
        console.log(`Loading item IDs from local file: ${inputPath}`);
        return await readFile(inputPath, 'utf-8');
    } else {
        console.log('Fetching item IDs from GitHub...');
        return await fetchItemIdsJson();
    }
}

async function getAllFiles(dir: string, baseDir: string = dir): Promise<string[]> {
    const files: string[] = [];
    const entries = await readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
        const fullPath = join(dir, entry.name);
        if (entry.isDirectory()) {
            files.push(...await getAllFiles(fullPath, baseDir));
        } else {
            files.push(relative(baseDir, fullPath));
        }
    }

    return files;
}

async function copyTemplateFile(
    templateDir: string,
    outputDir: string,
    fileName: string
): Promise<void> {
    const sourcePath = join(templateDir, fileName);
    const destPath = join(outputDir, fileName);
    await mkdir(dirname(destPath), { recursive: true });

    switch (fileName) {
        case 'package.json': {
            const packageJsonContent = await readFile(sourcePath, 'utf-8');
            const packageJson = JSON.parse(packageJsonContent);
            packageJson.name = 'mcbe-item-ids';
            packageJson.description = 'Minecraft Bedrock Edition item IDs';
            await writeFile(
                destPath,
                JSON.stringify(packageJson, null, 4),
                'utf-8'
            );
            break;
        }

        case 'README.md': {
            const readmeContent = await readFile(sourcePath, 'utf-8');
            const modifiedReadme = readmeContent
                .replace(/mcbe-item-ids-package-template/g, 'mcbe-item-ids')
                .replace(
                    'A TypeScript library template for creating MCBE Item IDs package.',
                    'Minecraft Bedrock Edition item IDs. Generated by [`mcbe-item-ids-packgen`](../mcbe-item-ids-packgen) based on the template [`mcbe-item-ids-package-template`](../mcbe-item-ids-package-template) and the JSON web-scraped with [`mcbe-item-ids-scraper`](../mcbe-item-ids-scraper) from <https://learn.microsoft.com/en-us/minecraft/creator/reference/content/vanillalistingsreference/items?view=minecraft-bedrock-stable>.'
                );
            await writeFile(destPath, modifiedReadme, 'utf-8');
            break;
        }

        default: {
            await copyFile(sourcePath, destPath);
            break;
        }
    }
}

async function createPackage(outputDir: string, inputPath?: string): Promise<void> {
    const templateDir = join(__dirname, '..', '..', 'mcbe-item-ids-package-template');

    const itemIdsJson = await loadItemIdsJson(inputPath);

    console.log('Creating package structure...');

    // Get all files from template
    const templateFiles = await getAllFiles(templateDir);

    // Copy all template files with special handling
    for (const fileName of templateFiles) {
        await copyTemplateFile(templateDir, outputDir, fileName);
    }

    // Save item IDs JSON
    const assetsDir = join(outputDir, 'assets');
    await mkdir(assetsDir, { recursive: true });
    await writeFile(
        join(assetsDir, 'item-ids.json'),
        itemIdsJson,
        'utf-8'
    );

    console.log(`Package created at: ${outputDir}`);
}

async function main() {
    const program = new Command();

    program
        .name(packageJson.name)
        .description(packageJson.description)
        .version(packageJson.version)
        .option('-i, --input <path>', 'Path to local item IDs JSON file (defaults to fetching from GitHub)');

    program.parse();

    const options = program.opts<{ input?: string }>();
    const outputDir = join(__dirname, '..', '..', 'mcbe-item-ids');

    await createPackage(outputDir, options.input);

    console.log('Done!');
}

main().catch((error) => {
    console.error('Error in main:', error);
    process.exit(1);
});
